import { defineConfig, devices } from "@playwright/test";

// Drive the real Bridza app in Chromium. The dev server runs with a STUB tool
// (BRIDZA_TOOL_OVERRIDE) so stage runs are instant + deterministic — no opencode.
const PORT = 5199;
const STUB = JSON.stringify({
  bin: "sh",
  args: ["-c", "echo '[stub] generating…'; echo 'generated by the e2e stub' > OUTPUT.md; echo '[stub] done'"],
});

export default defineConfig({
  testDir: "./e2e",
  timeout: 180_000,
  expect: { timeout: 20_000 },
  fullyParallel: false,
  workers: 1,
  retries: 0,
  reporter: [["list"]],
  globalSetup: "./e2e/global-setup.js",
  use: { baseURL: `http://localhost:${PORT}`, trace: "on-first-retry" },
  projects: [{ name: "chromium", use: { ...devices["Desktop Chrome"] } }],
  webServer: {
    command: `npx vite --port ${PORT} --strictPort`,
    env: { BRIDZA_TOOL_OVERRIDE: STUB },
    url: `http://localhost:${PORT}`,
    reuseExistingServer: false,
    timeout: 60_000,
  },
});
